"""经验池打分件（S9.2「perfect_judges 接真实 LLM」的落地半边，源 exp_pool/scorers/ 的 `复`）。

源 perfect_judges（SimplePerfectJudge：req 逐字相等 + 满分即完美）在本仓已由**余弦阈值**
承担（decorator.py 分叉注 ①，判定表在册）——它是规则不是 LLM；真正"接真实 LLM"的是
**scorer**：`SimpleScorer` 用源模板逐字，把一次 req→resp 的产物质量评成分数。
此前 FakeLLM 下打分无意义（判定表原话"推迟到终验之后"），S9 起由 manual 通道消费：
`tests/manual_judge_quality.py` 用真网关评 SOP 产物质量，落 storage/benchmark/s9_judged_quality.json。

偏离在册：源 `SimpleScorer.llm` 缺省 `Field(default_factory=LLM)`（import 即建真客户端）；
本仓改**惰性**（evaluate 时才建）——门禁/离线环境没有 LLM 配置，构造期建客户端是颗雷。
"""
import json
from typing import Optional

from pydantic import BaseModel

from codeharness.exp_pool.schema import Score
from codeharness.utils.common import CodeParser

SIMPLE_SCORER_TEMPLATE = """
Role: You are a highly efficient assistant, tasked with evaluating a response to a given request. The response is generated by a large language model (LLM). 

I will provide you with a request and a corresponding response. Your task is to assess this response and provide a score from a human perspective.

## Context
### Request
{req}

### Response
{resp}

## Format Example
```json
{{
    "val": "the value of the score, int from 1 to 10, higher is better.",
    "reason": "an explanation supporting the score."
}}
```

## Instructions
- Understand the request and response given by the user.
- Evaluate the response based on its quality relative to the given request.
- Provide a score from 1 to 10, where 10 is the best.
- Provide a reason supporting your score.

## Constraint
Format: Just print the result in json format like **Format Example**.

## Action
Follow instructions, generate output and make sure it follows the **Constraint**.
"""


class BaseScorer(BaseModel):
    """= 源 scorers/base.py：评一次 req→resp 的质量。"""

    async def evaluate(self, req: str, resp: str) -> Score:
        raise NotImplementedError


class SimpleScorer(BaseScorer):
    """= 源 scorers/simple.py：LLM 打分 1-10。llm 可注入 FakeLLM（门禁）或留 None（惰性真网关）。"""

    llm: Optional[object] = None

    async def evaluate(self, req: str, resp: str) -> Score:
        if self.llm is None:
            from codeharness.provider.gateway import LLMGateway
            self.llm = LLMGateway()
        prompt = SIMPLE_SCORER_TEMPLATE.format(req=req, resp=resp)
        raw = await self.llm.aask(prompt, tag="SimpleScorer")
        return Score(**json.loads(CodeParser.parse_code(raw, lang="json")))
